# Generated by Django 4.2.4 on 2023-08-02 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='date_added',
        ),
    ]
